"""Configuration values for the Hex strategy project."""

from pathlib import Path
import sys

# Prefer local project modules when multiple game folders are on sys.path.
_PROJECT_ROOT = Path(__file__).resolve().parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

# Allow local workspace runs without installing bgds globally.
_WORKSPACE_ROOT = Path(__file__).resolve().parents[1]
_BGDS_SRC = _WORKSPACE_ROOT / "bazza-game-design-system" / "src"
if _BGDS_SRC.exists() and str(_BGDS_SRC) not in sys.path:
    sys.path.insert(0, str(_BGDS_SRC))

from bgds.boards.hex import HEX_BOARD_STANDARD, HEX_RENDER_STANDARD
from bgds.visual.icons import (
    ICON_PATH_DANGER_24,
    ICON_PATH_FOREST_24,
    ICON_PATH_MOUNTAIN_24,
    ICON_PATH_PAWN_64_FILLED,
    ICON_PATH_QUEEN_64_FILLED,
)
from bgds.visual.typography import (
    FONT_FAMILY_DEFAULT,
    FONT_PATH_ROBOTO_BOLD,
    FONT_PATH_ROBOTO_REGULAR,
    FONT_SIZE_STATUS_DEFAULT,
    FONT_SIZE_UNIT_DEFAULT,
    STATUS_SEPARATOR_SLASH,
)

# Runtime
FPS = 30
WINDOW_TITLE = "Hex Game"

# Board dimensions
SCREEN_WIDTH = HEX_BOARD_STANDARD.screen_width_px
SCREEN_HEIGHT = HEX_BOARD_STANDARD.screen_height_px
BB_HEIGHT = HEX_BOARD_STANDARD.bottom_bar_height_px
TARGET_HEX_COUNT = HEX_BOARD_STANDARD.target_hex_count

# Rendering
FONT_NAME_BAR = FONT_FAMILY_DEFAULT
FONT_NAME_UNITS = FONT_FAMILY_DEFAULT
FONT_PATH_REGULAR = FONT_PATH_ROBOTO_REGULAR
FONT_PATH_UNITS = FONT_PATH_ROBOTO_BOLD
FONT_SIZE_BAR = FONT_SIZE_STATUS_DEFAULT
FONT_SIZE_UNITS = FONT_SIZE_UNIT_DEFAULT
UI_STATUS_SEPARATOR = STATUS_SEPARATOR_SLASH
UI_SELECTION_HIGHLIGHT_SCALE = HEX_RENDER_STANDARD.selection_highlight_scale
UI_MIN_LINE_WIDTH_PX = HEX_RENDER_STANDARD.min_line_width_px
UI_GRID_LINE_WIDTH_PX = HEX_RENDER_STANDARD.grid_line_width_px
UI_SELECTED_LINE_WIDTH_EXTRA_PX = HEX_RENDER_STANDARD.selected_line_width_extra_px
UI_RIVER_LINE_WIDTH_DELTA_PX = HEX_RENDER_STANDARD.adjacency_edge_line_width_delta_px
UI_EDGE_HALF_LENGTH_RATIO = HEX_RENDER_STANDARD.edge_half_length_ratio
UI_TERRAIN_MARKER_Y_OFFSET_SCALE = HEX_RENDER_STANDARD.cell_overlay_y_offset_scale
UI_TERRAIN_ICON_SIZE_SCALE = HEX_RENDER_STANDARD.cell_overlay_icon_size_scale
UI_EXPOSED_ICON_Y_OFFSET_SCALE = HEX_RENDER_STANDARD.top_overlay_y_offset_scale
UI_EXPOSED_ICON_SIZE_SCALE = HEX_RENDER_STANDARD.top_overlay_icon_size_scale
UI_CAPITAL_ICON_SIZE_SCALE = HEX_RENDER_STANDARD.center_primary_icon_size_scale
UI_CAPITAL_ICON_ALPHA = HEX_RENDER_STANDARD.center_primary_icon_alpha
UI_TOWN_ICON_SIZE_SCALE = HEX_RENDER_STANDARD.center_secondary_icon_size_scale
UI_TOWN_ICON_ALPHA = HEX_RENDER_STANDARD.center_secondary_icon_alpha
UI_SETTLEMENT_TROOP_Y_OFFSET_SCALE = HEX_RENDER_STANDARD.center_label_y_offset_scale

# Local icon identity for this game.
ICON_PATH_FOREST = ICON_PATH_FOREST_24
ICON_PATH_MOUNTAIN = ICON_PATH_MOUNTAIN_24
ICON_PATH_DANGER = ICON_PATH_DANGER_24
ICON_PATH_CAPITAL = ICON_PATH_QUEEN_64_FILLED
ICON_PATH_TOWN = ICON_PATH_PAWN_64_FILLED

# Domain identifiers
OWNER_NEUTRAL = 0
OWNER_P1 = 1
OWNER_P2 = 2
OWNER_PLAYER = OWNER_P1
OWNER_CPU = OWNER_P2

TERRAIN_PLAIN = 0
TERRAIN_MOUNTAIN = 1
TERRAIN_FOREST = 2

# Turn phases
PHASE_DEPLOYMENT = "Deployment"
PHASE_ATTACK = "Attack"
PHASE_MOVEMENT = "Movement"
MAX_MOVEMENT_SOURCE_HEXES = 3

# Gameplay tuning
DEPLOY_CHUNKS_PER_TURN = 3
UNITS_PER_DEPLOY_CHUNK = 3
DEPLOY_BONUS_CHUNKS_PER_SUPPLIED_TOWN = 1
CITIES_PER_PLAYER = 3
CITY_MIN_FRONTLINE_DISTANCE = 2
CITY_MIN_PAIR_DISTANCE = 2
CITY_SPACING_MARGIN = 1
CITY_PLACEMENT_MAX_COMBINATIONS = 36_000
REINFORCEMENTS_PER_TURN = DEPLOY_CHUNKS_PER_TURN * UNITS_PER_DEPLOY_CHUNK
REINFORCEMENTS_PER_PLAYER = REINFORCEMENTS_PER_TURN
TROOP_CAP_MOUNTAIN = 3
TROOP_CAP_PLAIN_FOREST = 6
TROOP_CAP_TOWN = 9
CAMPAIGN_LEVELS = 3
CPU_ACTION_DELAY_SECONDS = 2.0
CPU_DEPLOY_ACTION_DELAY_SECONDS = 0.5

# Combat model tuning (attacker-centric deltas).
COMBAT_BASE_ATTACKER_CHANCE = 0.50
COMBAT_GLOBAL_DEFENDER_BIAS_ATTACKER_DELTA = 0.00
COMBAT_MOUNTAIN_DEFENDER_ATTACKER_DELTA = -0.10
COMBAT_RIVER_CROSSING_ATTACKER_DELTA = -0.10
COMBAT_EXPOSED_DEFENDER_ATTACKER_DELTA = 0.20
COMBAT_MIN_ATTACKER_CHANCE = 0.10
COMBAT_MAX_ATTACKER_CHANCE = 0.90

# Terrain generation ranges
MIN_RIVERS = 1
MAX_RIVERS = 3
MIN_FOREST_CLUSTERS = 2
MAX_FOREST_CLUSTERS = 5
MAX_FORESTS_PER_CLUSTER = 5
MIN_MOUNTAIN_CLUSTERS = 2
MAX_MOUNTAIN_CLUSTERS = 5
MAX_MOUNTAINS_PER_CLUSTER = 5
