# Screen and Grid Dimensions
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800
BB_HEIGHT = 36
FPS = 30
WINDOW_TITLE = "Hex Game"

# Target total number of hexes on the board (best-fit within screen bounds).
# Must be >= 2; odd values are rounded down to the nearest even value.
GRID_HEX_COUNT = 80
FONT_NAME_BAR = None
FONT_NAME_UNITS = None
FONT_PATH_REGULAR = "assets/fonts/Roboto-Regular.ttf"
FONT_SIZE_BAR = 20
FONT_SIZE_UNITS = 20

### Colors
# Players
COLOR_P1_LIGHT = (102, 212, 200)
COLOR_P1_DARK  = (38, 110, 105)
COLOR_P2_LIGHT = (244, 137, 120)
COLOR_P2_DARK  = (150, 62, 54)
# Neutrals
COLOR_NEUTRAL_DARK  = (97, 101, 107)
COLOR_NEUTRAL_LIGHT = (230, 231, 235)
# UI surfaces
COLOR_BACKGROUND = (28, 30, 36)
COLOR_BOTTOM_BAR = (18, 18, 22)
# Text & highlights
COLOR_SCORE    = (238, 238, 242)
COLOR_SELECTED = (255, 224, 130)
# Terrain
COLOR_RIVER = (125, 160, 175)

# UI Tuning
UI_STATUS_SEPARATOR = "  |  "
UI_SELECTION_HIGHLIGHT_SCALE = 0.90
UI_MIN_LINE_WIDTH_PX = 2
UI_GRID_LINE_WIDTH_PX = 4
UI_SELECTED_LINE_WIDTH_EXTRA_PX = 1
UI_RIVER_LINE_WIDTH_DELTA_PX = -1
UI_EDGE_HALF_LENGTH_RATIO = 0.50
UI_TERRAIN_MARKER_Y_OFFSET_SCALE = 0.62
UI_TERRAIN_ICON_SIZE_SCALE = 0.42
UI_EXPOSED_ICON_Y_OFFSET_SCALE = 0.62
UI_EXPOSED_ICON_SIZE_SCALE = 0.28
ICON_PATH_FOREST = "assets/icons/forest_24.png"
ICON_PATH_MOUNTAIN = "assets/icons/mountain_24.png"
ICON_PATH_DANGER = "assets/icons/danger_24.png"
ICON_PATH_CAPITAL = "assets/icons/queen_64_filled.png"
ICON_PATH_TOWN = "assets/icons/pawn_64_filled.png"
UI_CAPITAL_ICON_SIZE_SCALE = 1.35
UI_CAPITAL_ICON_ALPHA = 128
UI_TOWN_ICON_SIZE_SCALE = UI_CAPITAL_ICON_SIZE_SCALE
UI_TOWN_ICON_ALPHA = UI_CAPITAL_ICON_ALPHA
UI_SETTLEMENT_TROOP_Y_OFFSET_SCALE = 0.14

OWNER_NEUTRAL = 0
OWNER_P1 = 1
OWNER_P2 = 2
OWNER_PLAYER = OWNER_P1
OWNER_CPU = OWNER_P2

TERRAIN_PLAIN = 0
TERRAIN_MOUNTAIN = 1
TERRAIN_FOREST = 2

PHASE_DEPLOYMENT = "Deployment"
PHASE_ATTACK = "Attack"
PHASE_MOVEMENT = "Movement"
MAX_MOVEMENT_SOURCE_HEXES = 3

DEPLOY_CHUNKS_PER_TURN = 3
UNITS_PER_DEPLOY_CHUNK = 3
DEPLOY_BONUS_CHUNKS_PER_SUPPLIED_TOWN = 1
CITIES_PER_PLAYER = 3
CITY_MIN_FRONTLINE_DISTANCE = 2
CITY_MIN_PAIR_DISTANCE = 2
CITY_SPACING_MARGIN = 1
CITY_PLACEMENT_MAX_COMBINATIONS = 36000
REINFORCEMENTS_PER_TURN = DEPLOY_CHUNKS_PER_TURN * UNITS_PER_DEPLOY_CHUNK
REINFORCEMENTS_PER_PLAYER = REINFORCEMENTS_PER_TURN
TROOP_CAP_MOUNTAIN = 3
TROOP_CAP_PLAIN_FOREST = 6
TROOP_CAP_TOWN = 9
CAMPAIGN_LEVELS = 3
CPU_ACTION_DELAY_SECONDS = 2.0
CPU_DEPLOY_ACTION_DELAY_SECONDS = 0.5

# Combat model tuning (attacker-centric deltas).
COMBAT_BASE_ATTACKER_CHANCE = 0.50
COMBAT_GLOBAL_DEFENDER_BIAS_ATTACKER_DELTA = 0.00
COMBAT_MOUNTAIN_DEFENDER_ATTACKER_DELTA = -0.10
COMBAT_RIVER_CROSSING_ATTACKER_DELTA = -0.10
COMBAT_EXPOSED_DEFENDER_ATTACKER_DELTA = 0.20
COMBAT_MIN_ATTACKER_CHANCE = 0.10
COMBAT_MAX_ATTACKER_CHANCE = 0.90

MIN_RIVERS = 1
MAX_RIVERS = 3
MIN_FOREST_CLUSTERS = 2
MAX_FOREST_CLUSTERS = 5
MAX_FORESTS_PER_CLUSTER = 5
MIN_MOUNTAIN_CLUSTERS = 2
MAX_MOUNTAIN_CLUSTERS = 5
MAX_MOUNTAINS_PER_CLUSTER = 5
