# Screen and Grid Dimensions
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700
BB_HEIGHT = 36
FPS = 30
WINDOW_TITLE = "Hex Game"

# Target total number of hexes on the board (best-fit within screen bounds).
# Must be >= 2; odd values are rounded down to the nearest even value.
GRID_HEX_COUNT = 120
FONT_NAME_BAR = None
FONT_NAME_UNITS = None
FONT_SIZE_BAR = 24
FONT_SIZE_UNITS = 24
FONT_SIZE_TERRAIN = 14
FONT_SIZE_TERRAIN_TAG = 12

# Colors
COLOR_P1_LIGHT = (80, 240, 220)
COLOR_P1_DARK = (25, 105, 100)
COLOR_P2_LIGHT = (250, 125, 110)
COLOR_P2_DARK = (140, 50, 45)

COLOR_NEUTRAL_DARK = (105, 105, 110)
COLOR_NEUTRAL_LIGHT = (220, 220, 225)
COLOR_BACKGROUND = (30, 30, 40)
COLOR_BOTTOM_BAR = (0, 0, 0)
COLOR_SCORE = (245, 245, 245)
COLOR_SELECTED = (255, 235, 120)
COLOR_RIVER = (120, 155, 170)

# UI Tuning
UI_STATUS_SEPARATOR = "     |     "
UI_SELECTION_HIGHLIGHT_SCALE = 0.90
UI_MIN_LINE_WIDTH_PX = 2
UI_GRID_LINE_WIDTH_PX = 4
UI_SELECTED_LINE_WIDTH_EXTRA_PX = 1
UI_RIVER_LINE_WIDTH_DELTA_PX = -1
UI_EDGE_HALF_LENGTH_RATIO = 0.50
UI_TERRAIN_MARKER_Y_OFFSET_SCALE = 0.62
UI_EXPOSED_DOT_Y_OFFSET_SCALE = 0.72
UI_EXPOSED_DOT_RADIUS_PX = 2
UI_TERRAIN_TAG_X_OFFSET_SCALE = 0.42
UI_TERRAIN_TAG_Y_OFFSET_SCALE = -0.02
UI_TERRAIN_TAG_MOUNTAIN = "+1D"
UI_TERRAIN_TAG_FOREST = "HID"
UI_TERRAIN_TAG_EXPOSED = "-1D"
UI_TERRAIN_MARK_FOREST = "F"
UI_TERRAIN_MARK_MOUNTAIN = "M"

OWNER_NEUTRAL = 0
OWNER_P1 = 1
OWNER_P2 = 2
OWNER_PLAYER = OWNER_P1
OWNER_CPU = OWNER_P2

TERRAIN_PLAIN = 0
TERRAIN_MOUNTAIN = 1
TERRAIN_FOREST = 2

PHASE_DEPLOYMENT = "Deployment"
PHASE_ATTACK = "Attack"
PHASE_MOVEMENT = "Movement"

DEPLOY_CHUNKS_PER_TURN = 4
UNITS_PER_DEPLOY_CHUNK = 2
REINFORCEMENTS_PER_TURN = DEPLOY_CHUNKS_PER_TURN * UNITS_PER_DEPLOY_CHUNK
REINFORCEMENTS_PER_PLAYER = REINFORCEMENTS_PER_TURN
MAX_TROOPS_PER_CELL = 9
MAX_ATTACKS_PER_TURN = 3
CAMPAIGN_LEVELS = 3
CPU_ACTION_DELAY_SECONDS = 2.0
CPU_DEPLOY_ACTION_DELAY_SECONDS = 0.5

MIN_RIVERS = 1
MAX_RIVERS = 3
MIN_FOREST_CLUSTERS = 2
MAX_FOREST_CLUSTERS = 5
MAX_FORESTS_PER_CLUSTER = 5
MIN_MOUNTAIN_CLUSTERS = 2
MAX_MOUNTAIN_CLUSTERS = 5
MAX_MOUNTAINS_PER_CLUSTER = 5
