"""Visual constants and asset helpers."""

from .assets import resolve_font_path, resolve_icon_path
from .colors import (
    COLOR_AMBER,
    COLOR_AQUA,
    COLOR_BRICK_RED,
    COLOR_CHARCOAL,
    COLOR_CORAL,
    COLOR_DEEP_TEAL,
    COLOR_FOG_GRAY,
    COLOR_NEAR_BLACK,
    COLOR_SLATE_GRAY,
    COLOR_SOFT_WHITE,
    COLOR_STEEL_BLUE,
)
from .icons import (
    ICON_PATH_DANGER_24,
    ICON_PATH_FOREST_24,
    ICON_PATH_MOUNTAIN_24,
    ICON_PATH_PAWN_64_FILLED,
    ICON_PATH_QUEEN_64_FILLED,
)
from .theme import (
    FONT_FAMILY_DEFAULT,
    FONT_PATH_ROBOTO_BOLD,
    FONT_PATH_ROBOTO_REGULAR,
    FONT_SIZE_STATUS_DEFAULT,
    FONT_SIZE_UNIT_DEFAULT,
    STATUS_SEPARATOR_SLASH,
)

__all__ = [
    "COLOR_AQUA",
    "COLOR_DEEP_TEAL",
    "COLOR_CORAL",
    "COLOR_BRICK_RED",
    "COLOR_SLATE_GRAY",
    "COLOR_FOG_GRAY",
    "COLOR_CHARCOAL",
    "COLOR_NEAR_BLACK",
    "COLOR_SOFT_WHITE",
    "COLOR_AMBER",
    "COLOR_STEEL_BLUE",
    "FONT_FAMILY_DEFAULT",
    "FONT_PATH_ROBOTO_REGULAR",
    "FONT_PATH_ROBOTO_BOLD",
    "FONT_SIZE_STATUS_DEFAULT",
    "FONT_SIZE_UNIT_DEFAULT",
    "STATUS_SEPARATOR_SLASH",
    "ICON_PATH_FOREST_24",
    "ICON_PATH_MOUNTAIN_24",
    "ICON_PATH_DANGER_24",
    "ICON_PATH_QUEEN_64_FILLED",
    "ICON_PATH_PAWN_64_FILLED",
    "resolve_font_path",
    "resolve_icon_path",
]
