"""Central configuration for Hex Game."""

from __future__ import annotations

# Runtime
FPS = 30
WINDOW_TITLE = "Hex Game"

# Board dimensions
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800
BB_HEIGHT = 36
TARGET_HEX_COUNT = 80

# Rendering
FONT_FAMILY_DEFAULT: str | None = None
FONT_NAME_BAR = FONT_FAMILY_DEFAULT
FONT_NAME_UNITS = FONT_FAMILY_DEFAULT
FONT_PATH_REGULAR = "fonts/Roboto-Regular.ttf"
FONT_PATH_UNITS = "fonts/Roboto-Bold.ttf"
FONT_SIZE_BAR = 20
FONT_SIZE_UNITS = 20
UI_STATUS_SEPARATOR = "   /   "

UI_SELECTION_HIGHLIGHT_SCALE = 0.90
UI_MIN_LINE_WIDTH_PX = 2
UI_GRID_LINE_WIDTH_PX = 4
UI_SELECTED_LINE_WIDTH_EXTRA_PX = 1
UI_RIVER_LINE_WIDTH_DELTA_PX = -1
UI_EDGE_HALF_LENGTH_RATIO = 0.50
UI_TERRAIN_MARKER_Y_OFFSET_SCALE = 0.62
UI_TERRAIN_ICON_SIZE_SCALE = 0.42
UI_EXPOSED_ICON_Y_OFFSET_SCALE = 0.62
UI_EXPOSED_ICON_SIZE_SCALE = 0.28
UI_CAPITAL_ICON_SIZE_SCALE = 1.35
UI_CAPITAL_ICON_ALPHA = 128
UI_TOWN_ICON_SIZE_SCALE = 1.35
UI_TOWN_ICON_ALPHA = 128
UI_SETTLEMENT_TROOP_Y_OFFSET_SCALE = 0.14

# Icons
ICON_PATH_FOREST = "icons/forest_24.png"
ICON_PATH_MOUNTAIN = "icons/mountain_24.png"
ICON_PATH_DANGER = "icons/danger_24.png"
ICON_PATH_CAPITAL = "icons/queen_64_filled.png"
ICON_PATH_TOWN = "icons/pawn_64_filled.png"

# Colors
COLOR_AQUA = (102, 212, 200)
COLOR_DEEP_TEAL = (38, 110, 105)
COLOR_CORAL = (244, 137, 120)
COLOR_BRICK_RED = (150, 62, 54)
COLOR_SLATE_GRAY = (97, 101, 107)
COLOR_FOG_GRAY = (230, 231, 235)
COLOR_CHARCOAL = (28, 30, 36)
COLOR_NEAR_BLACK = (18, 18, 22)
COLOR_SOFT_WHITE = (238, 238, 242)
COLOR_AMBER = (255, 224, 130)
COLOR_STEEL_BLUE = (125, 160, 175)

# Domain identifiers
OWNER_NEUTRAL = 0
OWNER_P1 = 1
OWNER_P2 = 2
OWNER_PLAYER = OWNER_P1
OWNER_CPU = OWNER_P2

TERRAIN_PLAIN = 0
TERRAIN_MOUNTAIN = 1
TERRAIN_FOREST = 2

# Turn phases
PHASE_DEPLOYMENT = "Deployment"
PHASE_ATTACK = "Attack"
PHASE_MOVEMENT = "Movement"
MAX_MOVEMENT_SOURCE_HEXES = 3

# Gameplay tuning
DEPLOY_CHUNKS_PER_TURN = 3
UNITS_PER_DEPLOY_CHUNK = 3
DEPLOY_BONUS_CHUNKS_PER_SUPPLIED_TOWN = 1
CITIES_PER_PLAYER = 3
CITY_MIN_FRONTLINE_DISTANCE = 2
CITY_MIN_PAIR_DISTANCE = 2
CITY_SPACING_MARGIN = 1
CITY_PLACEMENT_MAX_COMBINATIONS = 36_000
REINFORCEMENTS_PER_TURN = DEPLOY_CHUNKS_PER_TURN * UNITS_PER_DEPLOY_CHUNK
REINFORCEMENTS_PER_PLAYER = REINFORCEMENTS_PER_TURN
TROOP_CAP_MOUNTAIN = 3
TROOP_CAP_PLAIN_FOREST = 6
TROOP_CAP_TOWN = 9
CAMPAIGN_LEVELS = 3
CPU_ACTION_DELAY_SECONDS = 2.0
CPU_DEPLOY_ACTION_DELAY_SECONDS = 0.5

# Combat model tuning
COMBAT_BASE_ATTACKER_CHANCE = 0.50
COMBAT_GLOBAL_DEFENDER_BIAS_ATTACKER_DELTA = 0.00
COMBAT_MOUNTAIN_DEFENDER_ATTACKER_DELTA = -0.10
COMBAT_RIVER_CROSSING_ATTACKER_DELTA = -0.10
COMBAT_EXPOSED_DEFENDER_ATTACKER_DELTA = 0.20
COMBAT_MIN_ATTACKER_CHANCE = 0.10
COMBAT_MAX_ATTACKER_CHANCE = 0.90

# Terrain generation ranges
MIN_RIVERS = 1
MAX_RIVERS = 3
MIN_FOREST_CLUSTERS = 2
MAX_FOREST_CLUSTERS = 5
MAX_FORESTS_PER_CLUSTER = 5
MIN_MOUNTAIN_CLUSTERS = 2
MAX_MOUNTAIN_CLUSTERS = 5
MAX_MOUNTAINS_PER_CLUSTER = 5
